In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve
import matplotlib.pyplot as plt
df_sorted=pd.read_csv("/content/final_dataset.csv")
# Select only numeric features (excluding subject, session, epoch)
X = df_sorted.drop(columns=['subject', 'session', 'epoch', 'target'])  # Keep only features
y = df_sorted['target']  # Target labels

# Initialize KNN model
knn = KNeighborsClassifier(n_neighbors=5, weights='uniform', metric='euclidean')

# Train model on entire dataset
knn.fit(X, y)

# Predictions
y_pred = knn.predict(X)
y_pred_proba = knn.predict_proba(X)

# Evaluation Metrics
print("Accuracy:", accuracy_score(y, y_pred))
print("\nClassification Report:\n", classification_report(y, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y, y_pred))

# AUC-ROC (for multi-class classification)
auc_roc = roc_auc_score(y, y_pred_proba, multi_class='ovr')
print("\nAUC-ROC Score:", auc_roc)

# ROC Curve (Only if binary classification)
if len(set(y)) == 2:
    fpr, tpr, _ = roc_curve(y, y_pred_proba[:, 1])
    plt.plot(fpr, tpr, label="KNN (AUC = {:.3f})".format(auc_roc))
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.legend()
    plt.show()


Accuracy: 0.1668520578420467

Classification Report:
               precision    recall  f1-score   support

      cancel       0.00      0.00      0.00       596
        down       0.00      0.00      0.00       600
        left       0.00      0.00      0.00       600
       right       0.00      0.00      0.00       600
      select       0.00      0.00      0.00       600
          up       0.17      1.00      0.29       600

    accuracy                           0.17      3596
   macro avg       0.03      0.17      0.05      3596
weighted avg       0.03      0.17      0.05      3596


Confusion Matrix:
 [[  0   0   0   0   0 596]
 [  0   0   0   0   0 600]
 [  0   0   0   0   0 600]
 [  0   0   0   0   0 600]
 [  0   0   0   0   0 600]
 [  0   0   0   0   0 600]]

AUC-ROC Score: 0.5


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
