In [1]:
import pandas as pd
df=pd.read_csv("/content/cleaned_features.csv")
word_columns = ["subject", "session"]

# Ensure they exist in the dataframe
word_columns = [col for col in word_columns if col in df.columns]

# Separate word columns and numeric features
df_words = df[word_columns]  # Keep subject and session
df_features = df.drop(columns=word_columns)

In [2]:
print(df_features)

          ch0_mean       ch0_std       ch0_var  ch0_skew  ch0_kurtosis  \
0    -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
1    -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
2    -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
3    -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
4    -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
...            ...           ...           ...       ...           ...   
1381  2.429671e-30  6.357432e-22  4.041694e-43  0.208561     -0.343213   
1382  2.429671e-30  6.357432e-22  4.041694e-43  0.208561     -0.343213   
1383  2.429671e-30  6.357432e-22  4.041694e-43  0.208561     -0.343213   
1384  2.429671e-30  6.357432e-22  4.041694e-43  0.208561     -0.343213   
1385  2.429671e-30  6.357432e-22  4.041694e-43  0.208561     -0.343213   

      ch0_peak2peak      ch1_mean       ch1_std       ch1_var  ch1_skew  ...  \
0      2.541448e-21  4.132416e-

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
print(df_features.columns.tolist())

['ch0_mean', 'ch0_std', 'ch0_var', 'ch0_skew', 'ch0_kurtosis', 'ch0_peak2peak', 'ch1_mean', 'ch1_std', 'ch1_var', 'ch1_skew', 'ch1_kurtosis', 'ch1_peak2peak', 'ch2_mean', 'ch2_std', 'ch2_var', 'ch2_skew', 'ch2_kurtosis', 'ch2_peak2peak', 'ch3_mean', 'ch3_std', 'ch3_var', 'ch3_skew', 'ch3_kurtosis', 'ch3_peak2peak', 'ch4_mean', 'ch4_std', 'ch4_var', 'ch4_skew', 'ch4_kurtosis', 'ch4_peak2peak', 'ch5_mean', 'ch5_std', 'ch5_var', 'ch5_skew', 'ch5_kurtosis', 'ch5_peak2peak', 'ch6_mean', 'ch6_std', 'ch6_var', 'ch6_skew', 'ch6_kurtosis', 'ch6_peak2peak', 'ch7_mean', 'ch7_std', 'ch7_var', 'ch7_skew', 'ch7_kurtosis', 'ch7_peak2peak', 'ch8_mean', 'ch8_std', 'ch8_var', 'ch8_skew', 'ch8_kurtosis', 'ch8_peak2peak', 'ch9_mean', 'ch9_std', 'ch9_var', 'ch9_skew', 'ch9_kurtosis', 'ch9_peak2peak', 'ch10_mean', 'ch10_std', 'ch10_var', 'ch10_skew', 'ch10_kurtosis', 'ch10_peak2peak', 'ch11_mean', 'ch11_std', 'ch11_var', 'ch11_skew', 'ch11_kurtosis', 'ch11_peak2peak', 'ch12_mean', 'ch12_std', 'ch12_var', 'c

In [9]:
df2=pd.read_csv("/content/extracted_features (1).csv")
print(df2.columns.tolist())

['ch0_mean', 'ch0_std', 'ch0_var', 'ch0_skew', 'ch0_kurtosis', 'ch0_peak2peak', 'ch1_mean', 'ch1_std', 'ch1_var', 'ch1_skew', 'ch1_kurtosis', 'ch1_peak2peak', 'ch2_mean', 'ch2_std', 'ch2_var', 'ch2_skew', 'ch2_kurtosis', 'ch2_peak2peak', 'ch3_mean', 'ch3_std', 'ch3_var', 'ch3_skew', 'ch3_kurtosis', 'ch3_peak2peak', 'ch4_mean', 'ch4_std', 'ch4_var', 'ch4_skew', 'ch4_kurtosis', 'ch4_peak2peak', 'ch5_mean', 'ch5_std', 'ch5_var', 'ch5_skew', 'ch5_kurtosis', 'ch5_peak2peak', 'ch6_mean', 'ch6_std', 'ch6_var', 'ch6_skew', 'ch6_kurtosis', 'ch6_peak2peak', 'ch7_mean', 'ch7_std', 'ch7_var', 'ch7_skew', 'ch7_kurtosis', 'ch7_peak2peak', 'ch8_mean', 'ch8_std', 'ch8_var', 'ch8_skew', 'ch8_kurtosis', 'ch8_peak2peak', 'ch9_mean', 'ch9_std', 'ch9_var', 'ch9_skew', 'ch9_kurtosis', 'ch9_peak2peak', 'ch10_mean', 'ch10_std', 'ch10_var', 'ch10_skew', 'ch10_kurtosis', 'ch10_peak2peak', 'ch11_mean', 'ch11_std', 'ch11_var', 'ch11_skew', 'ch11_kurtosis', 'ch11_peak2peak', 'ch12_mean', 'ch12_std', 'ch12_var', 'c

In [10]:
print(df2["epoch"])

0         0
1         1
2         2
3         3
4         4
       ... 
3591    145
3592    146
3593    147
3594    148
3595    149
Name: epoch, Length: 3596, dtype: int64


In [11]:
import pandas as pd

# Load the extracted feature dataset
features_path = "/content/extracted_features (1).csv"  # Update with actual path
df = pd.read_csv(features_path)

# Expected trials per session
EXPECTED_TRIALS = 150
EXCEPTION_CASE = (6, 4)  # (Subject 6, Session 4) has 144 trials

# Count trials for each subject-session pair
trial_counts = df.groupby(['subject', 'session']).size().reset_index(name='num_trials')

# Check for mismatches
for _, row in trial_counts.iterrows():
    subj, sess, num_trials = row['subject'], row['session'], row['num_trials']
    expected = 144 if (subj, sess) == EXCEPTION_CASE else EXPECTED_TRIALS

    if num_trials != expected:
        print(f"⚠️ Mismatch for Subject {subj}, Session {sess}: Found {num_trials}, Expected {expected}")

# Display the trial counts
print(trial_counts)


⚠️ Mismatch for Subject sub-02, Session ses-01: Found 149, Expected 150
⚠️ Mismatch for Subject sub-04, Session ses-01: Found 149, Expected 150
⚠️ Mismatch for Subject sub-06, Session ses-03: Found 149, Expected 150
⚠️ Mismatch for Subject sub-08, Session ses-02: Found 149, Expected 150
   subject session  num_trials
0   sub-01  ses-01         150
1   sub-01  ses-02         150
2   sub-01  ses-03         150
3   sub-02  ses-01         149
4   sub-02  ses-02         150
5   sub-02  ses-03         150
6   sub-03  ses-01         150
7   sub-03  ses-02         150
8   sub-03  ses-03         150
9   sub-04  ses-01         149
10  sub-04  ses-02         150
11  sub-04  ses-03         150
12  sub-05  ses-01         150
13  sub-05  ses-02         150
14  sub-05  ses-03         150
15  sub-06  ses-01         150
16  sub-06  ses-02         150
17  sub-06  ses-03         149
18  sub-07  ses-01         150
19  sub-07  ses-02         150
20  sub-07  ses-03         150
21  sub-08  ses-01         150

In [12]:
import pandas as pd


# Expected trials per session
EXPECTED_TRIALS = 150
EXCEPTION_CASE = (6, 4)  # (Subject 6, Session 4) should have 144 trials

# Check for duplicate rows
duplicates = df.duplicated(subset=['subject', 'session'], keep=False)

if duplicates.any():
    print(f"⚠️ Warning: Found {duplicates.sum()} duplicate rows!")
    print(df[duplicates].head())

# Check for missing values
missing_values = df.isnull().sum().sum()
if missing_values > 0:
    print(f"⚠️ Warning: Found {missing_values} missing values!")

# Count unique trials per subject-session
trial_counts = df.groupby(['subject', 'session']).size().reset_index(name='num_trials')

# Find which rows are missing one trial
for _, row in trial_counts.iterrows():
    subj, sess, num_trials = row['subject'], row['session'], row['num_trials']
    expected = 144 if (subj, sess) == EXCEPTION_CASE else EXPECTED_TRIALS

    if num_trials != expected:
        print(f"🚨 Missing trials for Subject {subj}, Session {sess}: Found {num_trials}, Expected {expected}")
        # Show affected rows
        print(df[(df['subject'] == subj) & (df['session'] == sess)].head())

# Display trial counts summary
print(trial_counts)


⚠️ Warning: Found 3596 duplicate rows!
       ch0_mean       ch0_std       ch0_var  ch0_skew  ch0_kurtosis  \
0 -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
1 -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
2 -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
3 -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
4 -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   

   ch0_peak2peak      ch1_mean       ch1_std       ch1_var  ch1_skew  ...  \
0   2.541448e-21  4.132416e-30  3.358177e-22  1.127735e-43  0.429203  ...   
1   2.541448e-21  4.132416e-30  3.358177e-22  1.127735e-43  0.429203  ...   
2   2.541448e-21  4.132416e-30  3.358177e-22  1.127735e-43  0.429203  ...   
3   2.541448e-21  4.132416e-30  3.358177e-22  1.127735e-43  0.429203  ...   
4   2.541448e-21  4.132416e-30  3.358177e-22  1.127735e-43  0.429203  ...   

   ch25_entropy  ch26_entropy  ch27_entropy  ch28_entropy  ch29_entropy

In [13]:
import numpy as np

def find_missing_trials(df, subject, session):
    """Find missing trial numbers for a given subject and session."""
    subset = df[(df['subject'] == subject) & (df['session'] == session)]
    expected_trials = set(range(150))  # Expected trials: 0 to 149
    actual_trials = set(subset['epoch'].unique())

    missing_trials = expected_trials - actual_trials
    return missing_trials

# Check missing trials for the affected subjects
for subj, sess in [('sub-02', 'ses-01'), ('sub-04', 'ses-01'), ('sub-06', 'ses-03'), ('sub-08', 'ses-02')]:
    missing = find_missing_trials(df, subj, sess)
    if missing:
        print(f"🚨 Missing trials for {subj}, {sess}: {missing}")
    else:
        print(f"✅ No missing trial numbers detected for {subj}, {sess} (but still 149 trials).")


🚨 Missing trials for sub-02, ses-01: {149}
🚨 Missing trials for sub-04, ses-01: {149}
🚨 Missing trials for sub-06, ses-03: {149}
🚨 Missing trials for sub-08, ses-02: {149}


In [14]:
import numpy as np

# Define the fixed sequence of classes
target_classes = ['up', 'down', 'right', 'left', 'select', 'cancel']

def assign_labels(df):
    df = df.copy()
    assigned_targets = []

    for (subject, session), group in df.groupby(['subject', 'session']):
        num_trials = len(group)

        if num_trials not in [149, 150]:  # Unexpected case
            raise ValueError(f"Unexpected trial count {num_trials} for {subject}, {session}")

        # Generate labels for 150 trials
        full_labels = np.tile(target_classes, 25)  # Full 150-length sequence

        # If trials are missing (149 instead of 150), remove last label
        if num_trials == 149:
            full_labels = full_labels[:-1]  # Drop the last one

        assigned_targets.extend(full_labels[:num_trials])  # Assign exactly as needed

    df['target'] = assigned_targets
    return df

df = assign_labels(df)

# Verify correct assignment
print(df[['subject', 'session', 'epoch', 'target']].head(30))  # Check first 30 rows
print(df['target'].value_counts())  # Ensure balanced classes


   subject session  epoch  target
0   sub-01  ses-02      0      up
1   sub-01  ses-02      1    down
2   sub-01  ses-02      2   right
3   sub-01  ses-02      3    left
4   sub-01  ses-02      4  select
5   sub-01  ses-02      5  cancel
6   sub-01  ses-02      6      up
7   sub-01  ses-02      7    down
8   sub-01  ses-02      8   right
9   sub-01  ses-02      9    left
10  sub-01  ses-02     10  select
11  sub-01  ses-02     11  cancel
12  sub-01  ses-02     12      up
13  sub-01  ses-02     13    down
14  sub-01  ses-02     14   right
15  sub-01  ses-02     15    left
16  sub-01  ses-02     16  select
17  sub-01  ses-02     17  cancel
18  sub-01  ses-02     18      up
19  sub-01  ses-02     19    down
20  sub-01  ses-02     20   right
21  sub-01  ses-02     21    left
22  sub-01  ses-02     22  select
23  sub-01  ses-02     23  cancel
24  sub-01  ses-02     24      up
25  sub-01  ses-02     25    down
26  sub-01  ses-02     26   right
27  sub-01  ses-02     27    left
28  sub-01  se

In [18]:
god=pd.read_csv("/content/extracted_features (1).csv")

In [19]:
print(god)

          ch0_mean       ch0_std       ch0_var  ch0_skew  ch0_kurtosis  \
0    -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
1    -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
2    -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
3    -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
4    -4.692517e-30  4.383195e-22  1.921240e-43 -0.165564      0.074883   
...            ...           ...           ...       ...           ...   
3591 -5.464452e-31  2.382294e-22  5.675327e-44  0.203434     -0.078901   
3592 -5.464452e-31  2.382294e-22  5.675327e-44  0.203434     -0.078901   
3593 -5.464452e-31  2.382294e-22  5.675327e-44  0.203434     -0.078901   
3594 -5.464452e-31  2.382294e-22  5.675327e-44  0.203434     -0.078901   
3595 -5.464452e-31  2.382294e-22  5.675327e-44  0.203434     -0.078901   

      ch0_peak2peak      ch1_mean       ch1_std       ch1_var  ch1_skew  ...  \
0      2.541448e-21  4.132416e-

In [20]:
import pandas as pd

# Expected trials per session
expected_trials = 150
expected_trials_subject6_ses4 = 144  # Subject 6, Session 4 special case

# Count trials per subject-session
trial_counts = god.groupby(['subject', 'session']).size().reset_index(name='num_trials')

# Verify each subject-session pair
missing_sessions = []
incorrect_trials = []

for i in range(1, 9):  # Subjects 1-8
    for j in range(1, 4):  # Sessions 1-3
        subject = f"sub-{i:02d}"
        session = f"ses-{j:02d}"

        # Check if the subject-session pair exists
        match = trial_counts[(trial_counts['subject'] == subject) & (trial_counts['session'] == session)]

        if match.empty:
            missing_sessions.append((subject, session))
        else:
            trial_count = match.iloc[0]['num_trials']
            expected = expected_trials

            # Special case for subject-06 session-04
            if subject == "sub-06" and session == "ses-04":
                expected = expected_trials_subject6_ses4

            if trial_count != expected:
                incorrect_trials.append((subject, session, trial_count, expected))

# Print missing sessions
if missing_sessions:
    print("🚨 Missing subject-session pairs:")
    for sub, ses in missing_sessions:
        print(f"  - {sub}, {ses}")
else:
    print("✅ All subject-session pairs are present.")

# Print incorrect trial counts
if incorrect_trials:
    print("\n⚠️ Sessions with incorrect trial counts:")
    for sub, ses, found, expected in incorrect_trials:
        print(f"  - {sub}, {ses}: Found {found}, Expected {expected}")
else:
    print("✅ All subject-session pairs have correct trial counts.")


✅ All subject-session pairs are present.

⚠️ Sessions with incorrect trial counts:
  - sub-02, ses-01: Found 149, Expected 150
  - sub-04, ses-01: Found 149, Expected 150
  - sub-06, ses-03: Found 149, Expected 150
  - sub-08, ses-02: Found 149, Expected 150


In [21]:
subject = "sub-01"
session = "ses-01"

match = trial_counts[(trial_counts['subject'] == subject) & (trial_counts['session'] == session)]

if match.empty:
    print(f"🚨 {subject}, {session} is MISSING!")
else:
    trial_count = match.iloc[0]['num_trials']
    print(f"✅ {subject}, {session} is PRESENT with {trial_count} trials.")

✅ sub-01, ses-01 is PRESENT with 150 trials.


In [23]:
import numpy as np

# Sort dataset by subject and session
df_sorted = god.sort_values(by=["subject", "session", "epoch"]).reset_index(drop=True)

# Function to generate labels based on trial count
def assign_labels(trial_count, subject, session):
    base_labels = ['up'] * 25 + ['down'] * 25 + ['right'] * 25 + \
                  ['left'] * 25 + ['select'] * 25 + ['cancel'] * 25

    if subject == "sub-06" and session == "ses-04":  # Handle subject 6 case
        base_labels = ['up'] * 24 + ['down'] * 24 + ['right'] * 24 + \
                      ['left'] * 24 + ['select'] * 24 + ['cancel'] * 24

    return base_labels[:trial_count]  # Trim if trials are missing

# Apply labeling
df_sorted["target"] = np.concatenate([
    assign_labels(len(group), sub, ses)
    for (sub, ses), group in df_sorted.groupby(["subject", "session"])
])

# Verification step
print(df_sorted[["subject", "session", "epoch", "target"]].head(150))  # Check first few rows

# Save the cleaned dataset
df_sorted.to_csv("final_dataset.csv", index=False)
print("✅ Final dataset saved as 'final_dataset.csv'.")


    subject session  epoch  target
0    sub-01  ses-01      0      up
1    sub-01  ses-01      1      up
2    sub-01  ses-01      2      up
3    sub-01  ses-01      3      up
4    sub-01  ses-01      4      up
..      ...     ...    ...     ...
145  sub-01  ses-01    145  cancel
146  sub-01  ses-01    146  cancel
147  sub-01  ses-01    147  cancel
148  sub-01  ses-01    148  cancel
149  sub-01  ses-01    149  cancel

[150 rows x 4 columns]


KeyboardInterrupt: 

In [24]:
print(df_sorted)

          ch0_mean       ch0_std       ch0_var  ch0_skew  ch0_kurtosis  \
0    -1.365400e-34  2.253221e-26  5.077004e-52  0.305004     -0.156780   
1    -1.365400e-34  2.253221e-26  5.077004e-52  0.305004     -0.156780   
2    -1.365400e-34  2.253221e-26  5.077004e-52  0.305004     -0.156780   
3    -1.365400e-34  2.253221e-26  5.077004e-52  0.305004     -0.156780   
4    -1.365400e-34  2.253221e-26  5.077004e-52  0.305004     -0.156780   
...            ...           ...           ...       ...           ...   
3591  3.077641e-31  3.069497e-22  9.421811e-44 -0.374264     -0.397671   
3592  3.077641e-31  3.069497e-22  9.421811e-44 -0.374264     -0.397671   
3593  3.077641e-31  3.069497e-22  9.421811e-44 -0.374264     -0.397671   
3594  3.077641e-31  3.069497e-22  9.421811e-44 -0.374264     -0.397671   
3595  3.077641e-31  3.069497e-22  9.421811e-44 -0.374264     -0.397671   

      ch0_peak2peak      ch1_mean       ch1_std       ch1_var  ch1_skew  ...  \
0      1.254107e-25  4.032866e-

In [26]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Load dataset


# Drop non-numeric features
X = df_sorted.drop(columns=["subject", "session", "target"])  # Keep only numeric features
y = df_sorted["target"]  # Target variable

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train Logistic Regression model on full data
clf = LogisticRegression(max_iter=1000, solver='lbfgs', multi_class='multinomial', random_state=42)
clf.fit(X_scaled, y)

print("✅ Logistic Regression model trained on the full dataset!")


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


✅ Logistic Regression model trained on the full dataset!


In [27]:
df_sorted.to_csv("final_dataset.csv", index=False)

In [28]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Extract numeric features and target variable
X = df_sorted.drop(columns=["subject", "session", "target"])  # Remove non-numeric columns
y = df_sorted["target"]

# Perform cross-validation to get accuracy scores
logreg = LogisticRegression(max_iter=1000)
cv_scores = cross_val_score(logreg, X, y, cv=5, scoring='accuracy')

# Train on full dataset
logreg.fit(X, y)

# Predict on the same dataset
y_pred = logreg.predict(X)

# Print evaluation metrics
print(f"✅ Cross-Validation Accuracy: {np.mean(cv_scores):.4f} ± {np.std(cv_scores):.4f}")
print("\n📊 Classification Report:\n", classification_report(y, y_pred))
print("\n📉 Confusion Matrix:\n", confusion_matrix(y, y_pred))


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

✅ Cross-Validation Accuracy: 0.9497 ± 0.0177

📊 Classification Report:
               precision    recall  f1-score   support

      cancel       0.99      1.00      1.00       596
        down       0.99      0.99      0.99       600
        left       0.99      0.99      0.99       600
       right       0.99      0.98      0.98       600
      select       0.99      0.99      0.99       600
          up       0.99      0.99      0.99       600

    accuracy                           0.99      3596
   macro avg       0.99      0.99      0.99      3596
weighted avg       0.99      0.99      0.99      3596


📉 Confusion Matrix:
 [[594   0   0   0   2   0]
 [  0 592   0   5   0   3]
 [  0   0 593   3   4   0]
 [  0   3   7 590   0   0]
 [  3   0   0   0 597   0]
 [  0   5   0   0   0 595]]


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
