In [3]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
df_sorted=pd.read_csv("/content/final_dataset.csv")
# Extract numeric features and target variable
X = df_sorted.drop(columns=["subject", "session", "target"])  # Remove non-numeric columns
y = df_sorted["target"]

# Initialize SVM with an RBF kernel (good default)
svm_model = SVC(C=1.0, kernel="rbf", probability=True)  # Set probability=True for AUC-ROC

# Perform cross-validation for accuracy scores
cv_scores = cross_val_score(svm_model, X, y, cv=5, scoring='accuracy')

# Train on full dataset
svm_model.fit(X, y)

# Predict on the same dataset
y_pred = svm_model.predict(X)
y_pred_proba = svm_model.predict_proba(X)  # Get probability scores for AUC-ROC

# Compute AUC-ROC for multiclass classification
 # One-vs-Rest

# Print evaluation metrics
print(f" Cross-Validation Accuracy: {np.mean(cv_scores):.4f} ± {np.std(cv_scores):.4f}")

print("\n Classification Report:\n", classification_report(y, y_pred))
print("\n Confusion Matrix:\n", confusion_matrix(y, y_pred))


 Cross-Validation Accuracy: 1.0000 ± 0.0000

 Classification Report:
               precision    recall  f1-score   support

      cancel       1.00      1.00      1.00       596
        down       1.00      1.00      1.00       600
        left       1.00      1.00      1.00       600
       right       1.00      1.00      1.00       600
      select       1.00      1.00      1.00       600
          up       1.00      1.00      1.00       600

    accuracy                           1.00      3596
   macro avg       1.00      1.00      1.00      3596
weighted avg       1.00      1.00      1.00      3596


 Confusion Matrix:
 [[596   0   0   0   0   0]
 [  0 600   0   0   0   0]
 [  0   0 600   0   0   0]
 [  0   0   0 600   0   0]
 [  0   0   0   0 600   0]
 [  0   0   0   0   0 600]]
